import { verifyCompany,passesCompanyQualityGate } from "@/lib/company-verification";
import { buildDiscoveryQueries,normaliseResults } from "@/lib/discovery";
import { scrapeCompanyHomepage } from "@/lib/providers/crawler";
import { TavilySearchProvider } from "@/lib/providers/search";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { inngest } from "../client";

export const discoverProspects=inngest.createFunction({id:"discover-prospects",retries:3,triggers:{event:"prospects/discovery.requested"}},async({event,step})=>{
  const{runId,icpId,organisationId,limit}=event.data as {runId:string;icpId:string;organisationId:string;limit:number};
  if(!runId||!icpId||!organisationId)throw new Error("Start Company Discovery from the Prospect Intelligence OS so the ICP and organisation are supplied.");
  const admin=createSupabaseAdminClient();
  await step.run("mark-running",()=>admin.from("discovery_runs").update({status:"running",started_at:new Date().toISOString()}).eq("id",runId));
  try{
    const context=await step.run("load-company-discovery-context",async()=>{const[{data:icp,error:icpError},{data:org,error:orgError}]=await Promise.all([admin.from("icps").select("name,description,industries,excluded_industries,countries,regions,business_models,funding_stages,technologies,target_roles,target_departments,required_signals,preferred_signals,excluded_signals,keywords,company_size_min,company_size_max,default_service").eq("id",icpId).eq("organisation_id",organisationId).single(),admin.from("organisations").select("discovery_match_threshold").eq("id",organisationId).single()]);if(icpError||!icp)throw new Error("ICP not found");if(orgError||!org)throw new Error("Organisation settings not found");return{icp,threshold:org.discovery_match_threshold||70}});
    const queries=buildDiscoveryQueries(context.icp);const tavilyKey=process.env.TAVILY_API_KEY;if(!tavilyKey)throw new Error("TAVILY_API_KEY is not configured");const firecrawlKey=process.env.FIRECRAWL_API_KEY;if(!firecrawlKey)throw new Error("FIRECRAWL_API_KEY is not configured");const provider=new TavilySearchProvider(tavilyKey);
    await admin.from("discovery_runs").update({minimum_match_score:context.threshold,search_query:queries.join(" | ")}).eq("id",runId);
    const results=await step.run("discover-company-domains",async()=>{const perQuery=Math.max(8,Math.ceil(limit*1.5/queries.length));const groups=await Promise.all(queries.map(async query=>(await provider.search(query,perQuery)).map(result=>({...result,query}))));return groups.flat()});
    const candidates=normaliseResults(results).slice(0,Math.min(limit*2,60));const domains=candidates.map(x=>x.domain);const{data:existing}=domains.length?await admin.from("companies").select("domain").eq("organisation_id",organisationId).in("domain",domains):{data:[]};const existingDomains=new Set(existing?.map(x=>x.domain));const fresh=candidates.filter(x=>!existingDomains.has(x.domain));const qualified:Array<Record<string,unknown>>=[];const companyKeys=new Set<string>();
    for(const candidate of fresh){if(qualified.length>=limit)break;const result=await step.run(`verify-company-${candidate.domain}`.slice(0,100),async()=>{try{const page=await scrapeCompanyHomepage(candidate.websiteUrl,firecrawlKey);const verification=await verifyCompany(candidate,page,context.icp);return{page,verification}}catch{return null}});if(!result||!passesCompanyQualityGate(result.verification,context.threshold))continue;const companyKey=(result.verification.parent_company||result.verification.company_name).toLowerCase().replace(/[^a-z0-9]/g,"");if(companyKeys.has(companyKey))continue;companyKeys.add(companyKey);qualified.push({organisation_id:organisationId,name:result.verification.company_name,domain:candidate.domain,website_url:result.page.url,industry:result.verification.industry,description:result.verification.description,headquarters:result.verification.country,country:result.verification.country,employee_range:result.verification.employee_range,business_model:result.verification.business_model,products:result.verification.products,ideal_customers:[],technology_summary:null,source:"company_discovery",source_urls:[result.page.url,candidate.sourceUrl],discovery_run_id:runId,status:"pending_approval",match_explanation:result.verification.reason_it_matches,discovery_evidence:result.verification.evidence.join(" · "),discovery_confidence:result.verification.confidence,initial_icp_match_score:result.verification.match_score,verification_evidence:result.verification.evidence,verified_company:true,parent_company:result.verification.parent_company});}
    let imported=0;if(qualified.length){const{data,error}=await admin.from("companies").insert(qualified).select("id");if(error)throw error;imported=data?.length||0;}
    await admin.from("usage_events").insert([{organisation_id:organisationId,event_type:"discovery_search",quantity:queries.length,metadata:{run_id:runId,provider:"tavily"}},{organisation_id:organisationId,event_type:"firecrawl_page",quantity:fresh.length,metadata:{run_id:runId}},{organisation_id:organisationId,event_type:"openai_request",quantity:fresh.length,metadata:{run_id:runId,operation:"company_verification"}}]);
    await admin.from("discovery_runs").update({status:"completed",companies_found:candidates.length,companies_imported:imported,completed_at:new Date().toISOString()}).eq("id",runId);return{candidate_domains:candidates.length,verified_prospects:imported,threshold:context.threshold};
  }catch(error){await admin.from("discovery_runs").update({status:"failed",error_message:error instanceof Error?error.message:"Company Discovery failed",completed_at:new Date().toISOString()}).eq("id",runId);throw error;}
});
