import { describe, expect, it } from "vitest";
import { calculateDiscoveryOpportunityScore, passesDiscoveryOpportunityGate } from "./company-verification";
const base = { is_operating_business:true,is_commercial_organisation:true,has_identifiable_products_or_services:true,matches_icp:true,company_name:"Acme",parent_company:null,industry:"SaaS",description:"x",products:["Platform"],services:[],country:"UK",employee_range:"51 to 200",business_model:"B2B",buyer_intent_score:20,community_need_score:18,community_footprint_score:12,marketing_maturity_score:8,budget_ability_score:8,competitive_pressure_score:8,ai_search_importance_score:4,immediate_buying_signals_score:4,confidence_penalty:5,concrete_problem_evidenced:true,concrete_business_problem:"Buyers compare it publicly",why_they_would_buy:"To understand comparisons",high_score_evidence:[{claim:"Comparison pressure",evidence:"The site names alternatives",source_url:"https://acme.test"}],evidence:["Official site shows comparison pressure"],confidence:"high" as const,rejection_reason:null };
describe("Discovery opportunity score",()=>{
  it("scores buyer likelihood and subtracts confidence",()=>expect(calculateDiscoveryOpportunityScore(base)).toBe(77));
  it("caps the score at 80 without an evidenced problem",()=>expect(calculateDiscoveryOpportunityScore({...base,buyer_intent_score:25,community_need_score:20,community_footprint_score:15,marketing_maturity_score:10,budget_ability_score:10,competitive_pressure_score:10,ai_search_importance_score:5,immediate_buying_signals_score:5,confidence_penalty:0,concrete_problem_evidenced:false,high_score_evidence:[]})).toBe(80));
  it("allows rare scores above 80 only with explicit evidence",()=>expect(calculateDiscoveryOpportunityScore({...base,buyer_intent_score:25,community_need_score:20,community_footprint_score:15,marketing_maturity_score:10,budget_ability_score:10,competitive_pressure_score:10,ai_search_importance_score:5,immediate_buying_signals_score:5,confidence_penalty:5})).toBe(95));
  it("requires the operating business gate and threshold",()=>{const value={...base,match_score:77};expect(passesDiscoveryOpportunityGate(value,70)).toBe(true);expect(passesDiscoveryOpportunityGate({...value,is_commercial_organisation:false},70)).toBe(false);expect(passesDiscoveryOpportunityGate({...value,match_score:69},70)).toBe(false)});
});
