"use server";
import { getWorkspace, requirePermission } from "@/lib/workspace";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";

const textList=(value:FormDataEntryValue|null)=>String(value??"").split(",").map(x=>x.trim()).filter(Boolean);
const text=(form:FormData,name:string)=>String(form.get(name)??"").trim();
async function audit(action:string,entityType:string,entityId:string,metadata:Record<string,unknown>={}){const{ supabase,user,organisationId}=await getWorkspace();await supabase.from("audit_logs").insert({organisation_id:organisationId,user_id:user.id,action,entity_type:entityType,entity_id:entityId,metadata});}

const icpSchema=z.object({name:z.string().min(2).max(120),description:z.string().max(2000),company_size_min:z.number().int().nonnegative().nullable(),company_size_max:z.number().int().positive().nullable()}).refine(v=>v.company_size_min===null||v.company_size_max===null||v.company_size_min<=v.company_size_max,"Invalid company size range");
function icpPayload(form:FormData){const min=text(form,"company_size_min"),max=text(form,"company_size_max");const base=icpSchema.parse({name:text(form,"name"),description:text(form,"description"),company_size_min:min?Number(min):null,company_size_max:max?Number(max):null});return{...base,industries:textList(form.get("industries")),excluded_industries:textList(form.get("excluded_industries")),countries:textList(form.get("countries")),business_models:textList(form.get("business_models")),funding_stages:textList(form.get("funding_stages")),technologies:textList(form.get("technologies")),target_roles:textList(form.get("target_roles")),target_departments:textList(form.get("target_departments")),required_signals:textList(form.get("required_signals")),preferred_signals:textList(form.get("preferred_signals")),excluded_signals:textList(form.get("excluded_signals")),keywords:textList(form.get("keywords")),default_service:text(form,"default_service")||null};}

export async function createIcp(form:FormData){const{ supabase,user,organisationId,role}=await getWorkspace();requirePermission(role,"runDiscovery");const{data,error}=await supabase.from("icps").insert({...icpPayload(form),organisation_id:organisationId,created_by:user.id}).select("id").single();if(error)throw new Error(error.message);await audit("icp_created","icp",data.id);revalidatePath("/icps");redirect(`/icps/${data.id}?saved=created`);}
export async function updateIcp(id:string,form:FormData){const{ supabase,organisationId,role}=await getWorkspace();requirePermission(role,"runDiscovery");const{error}=await supabase.from("icps").update({...icpPayload(form),updated_at:new Date().toISOString()}).eq("id",id).eq("organisation_id",organisationId);if(error)throw new Error(error.message);await audit("icp_updated","icp",id);revalidatePath("/icps");revalidatePath(`/icps/${id}`);redirect(`/icps/${id}?saved=updated`);}

const companySchema=z.object({name:z.string().min(2).max(160),website:z.string().url()});
export async function addCompany(form:FormData){const{ supabase,user,organisationId,role}=await getWorkspace();requirePermission(role,"runDiscovery");const parsed=companySchema.parse({name:text(form,"name"),website:text(form,"website_url")});const url=new URL(parsed.website);const domain=url.hostname.toLowerCase().replace(/^www\./,"");const{data,error}=await supabase.from("companies").insert({organisation_id:organisationId,name:parsed.name,domain,website_url:url.toString(),source:"manual",source_urls:[url.toString()],status:"pending_approval",owner_user_id:user.id}).select("id").single();if(error?.code==="23505")redirect("/prospects?notice=That+company+already+exists");if(error)throw new Error(error.message);await audit("company_added","company",data.id,{source:"manual"});revalidatePath("/dashboard");revalidatePath("/prospects");redirect(`/prospects/${data.id}`);}

export async function setProspectStatus(companyId:string,status:"approved"|"rejected"){const{ supabase,user,organisationId,role}=await getWorkspace();requirePermission(role,"runDiscovery");const{error}=await supabase.from("companies").update({status,updated_at:new Date().toISOString()}).eq("id",companyId).eq("organisation_id",organisationId);if(error)throw new Error(error.message);await supabase.from("activities").insert({organisation_id:organisationId,company_id:companyId,user_id:user.id,activity_type:`prospect_${status}`,summary:`Prospect ${status}`});await audit(`prospect_${status}`,"company",companyId);revalidatePath("/dashboard");revalidatePath("/prospects");}

export async function saveProspect(companyId:string){const{supabase,organisationId,role}=await getWorkspace();requirePermission(role,"viewProspects");const now=new Date().toISOString();const{error}=await supabase.from("companies").update({saved_at:now,hidden_at:null,updated_at:now}).eq("id",companyId).eq("organisation_id",organisationId);if(error)throw new Error(error.message);revalidatePath("/dashboard");revalidatePath("/prospects");}
export async function removeSavedProspect(companyId:string){const{supabase,organisationId,role}=await getWorkspace();requirePermission(role,"viewProspects");const{error}=await supabase.from("companies").update({saved_at:null,updated_at:new Date().toISOString()}).eq("id",companyId).eq("organisation_id",organisationId);if(error)throw new Error(error.message);revalidatePath("/dashboard");revalidatePath("/prospects");}
export async function hideProspect(companyId:string){const{supabase,organisationId,role}=await getWorkspace();requirePermission(role,"viewProspects");const now=new Date().toISOString();const{error}=await supabase.from("companies").update({hidden_at:now,saved_at:null,updated_at:now}).eq("id",companyId).eq("organisation_id",organisationId);if(error)throw new Error(error.message);revalidatePath("/dashboard");revalidatePath("/prospects");}

const stages=["discovered","approved","researching","research_ready","outreach_ready","draft_created","contacted","replied","qualified","meeting_booked","proposal_sent","won","lost","paused"] as const;
export async function updatePipelineStage(opportunityId:string,form:FormData){const{ supabase,user,organisationId,role}=await getWorkspace();requirePermission(role,"managePipeline");const stage=z.enum(stages).parse(text(form,"stage"));const{data,error}=await supabase.from("pipeline_opportunities").update({stage,updated_at:new Date().toISOString(),won_at:stage==="won"?new Date().toISOString():null,lost_at:stage==="lost"?new Date().toISOString():null}).eq("id",opportunityId).eq("organisation_id",organisationId).select("company_id").single();if(error)throw new Error(error.message);await supabase.from("activities").insert({organisation_id:organisationId,company_id:data.company_id,user_id:user.id,activity_type:"pipeline_stage_changed",summary:`Pipeline moved to ${stage.replaceAll("_"," ")}`,details:{stage}});await audit("pipeline_stage_changed","pipeline_opportunity",opportunityId,{stage});revalidatePath("/pipeline");revalidatePath("/dashboard");}
export async function updateOpportunity(opportunityId:string,form:FormData){const{ supabase,organisationId,role}=await getWorkspace();requirePermission(role,"managePipeline");const amount=text(form,"estimated_value");const payload={estimated_value:amount?z.coerce.number().nonnegative().parse(amount):null,next_action:text(form,"next_action")||null,next_action_date:text(form,"next_action_date")||null,updated_at:new Date().toISOString()};const{error}=await supabase.from("pipeline_opportunities").update(payload).eq("id",opportunityId).eq("organisation_id",organisationId);if(error)throw new Error(error.message);await audit("pipeline_opportunity_updated","pipeline_opportunity",opportunityId,payload);revalidatePath("/pipeline");revalidatePath("/dashboard");}

export async function addNote(companyId:string,form:FormData){const{ supabase,user,organisationId,role}=await getWorkspace();requirePermission(role,"runResearch");const content=z.string().trim().min(1).max(5000).parse(form.get("content"));const{data,error}=await supabase.from("notes").insert({organisation_id:organisationId,company_id:companyId,author_user_id:user.id,content}).select("id").single();if(error)throw new Error(error.message);await audit("note_created","note",data.id,{company_id:companyId});revalidatePath(`/prospects/${companyId}`);}
export async function addTask(companyId:string,form:FormData){const{ supabase,user,organisationId,role}=await getWorkspace();requirePermission(role,"runResearch");const title=z.string().trim().min(2).max(200).parse(form.get("title"));const due=text(form,"due_at")||null;const{data,error}=await supabase.from("tasks").insert({organisation_id:organisationId,company_id:companyId,assigned_to:user.id,title,status:"open",priority:text(form,"priority")||"normal",due_at:due}).select("id").single();if(error)throw new Error(error.message);await audit("task_created","task",data.id,{company_id:companyId});revalidatePath(`/prospects/${companyId}`);revalidatePath("/dashboard");}
export async function completeTask(taskId:string,companyId:string){const{ supabase,organisationId,role}=await getWorkspace();requirePermission(role,"runResearch");const{error}=await supabase.from("tasks").update({status:"completed",completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",taskId).eq("organisation_id",organisationId);if(error)throw new Error(error.message);await audit("task_completed","task",taskId);revalidatePath(`/prospects/${companyId}`);revalidatePath("/dashboard");}
