import Link from "next/link";
import { ProspectCard, type FeedCompany } from "@/components/prospect-card";
import { PageHeader } from "@/components/page-header";
import { getWorkspace } from "@/lib/workspace";

const columns="id,name,domain,website_url,industry,country,headquarters,employee_range,funding_stage,description,match_explanation,verification_evidence,initial_icp_match_score,created_at,saved_at";
export default async function Dashboard(){const{supabase,organisationId}=await getWorkspace();const startToday=new Date();startToday.setHours(0,0,0,0);const week=new Date(Date.now()-7*86400000);const[{data:feed},{count:today},{count:thisWeek},{count:saved},{count:high}]=await Promise.all([
  supabase.from("companies").select(columns).eq("organisation_id",organisationId).is("hidden_at",null).not("initial_icp_match_score","is",null).order("initial_icp_match_score",{ascending:false}).order("created_at",{ascending:false}).limit(30),
  supabase.from("companies").select("id",{count:"exact",head:true}).eq("organisation_id",organisationId).is("hidden_at",null).gte("created_at",startToday.toISOString()),
  supabase.from("companies").select("id",{count:"exact",head:true}).eq("organisation_id",organisationId).is("hidden_at",null).gte("created_at",week.toISOString()),
  supabase.from("companies").select("id",{count:"exact",head:true}).eq("organisation_id",organisationId).not("saved_at","is",null),
  supabase.from("companies").select("id",{count:"exact",head:true}).eq("organisation_id",organisationId).is("hidden_at",null).gte("initial_icp_match_score",80),
]);const companies=(feed||[]) as FeedCompany[];const recentSaved=companies.filter(company=>company.saved_at).sort((a,b)=>String(b.saved_at).localeCompare(String(a.saved_at))).slice(0,3);return <>
  <PageHeader eyebrow="Opportunity Feed" title="Discover Your Next Customer" description="Prospect OS continuously finds companies that look like strong candidates for Community Intelligence services. Each discovery is an opportunity worth exploring." action={<Link href="/discover" className="button">Run Discovery</Link>}/>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["New Today",today||0],["New This Week",thisWeek||0],["High Discovery Scores",high||0],["Recently Saved",saved||0]].map(([label,value])=><div className="card p-4" key={label}><div className="label">{label}</div><div className="mt-2 text-3xl font-extrabold">{value}</div></div>)}</div>
  {recentSaved.length>0&&<section className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-extrabold">Recently Saved</h2><Link href="/prospects" className="font-bold text-[#c74c0b]">View My Prospect List</Link></div><div className="grid gap-5 xl:grid-cols-2">{recentSaved.map(company=><ProspectCard company={company} key={`saved-${company.id}`}/>)}</div></section>}
  <section className="mt-8"><div className="mb-4"><div className="label text-[#f36c21]">Opportunity Radar</div><h2 className="mt-1 text-2xl font-extrabold">Trending Prospects</h2><p className="mt-1 text-sm text-[#667085]">The most promising current discoveries, ranked by publicly available buying signals.</p></div>{companies.length?<div className="grid gap-5 xl:grid-cols-2">{companies.map(company=><ProspectCard company={company} key={company.id}/>)}</div>:<div className="card p-16 text-center"><h2 className="text-xl font-extrabold">Your opportunity feed is ready</h2><p className="mt-2 text-sm text-[#667085]">Run Discovery to find companies worth talking to.</p><Link href="/discover" className="button mt-5">Discover Potential Buyers</Link></div>}</section>
</>}
