import { ExternalLink, EyeOff, MapPin, Star, Users } from "lucide-react";
import { hideProspect, removeSavedProspect, saveProspect } from "@/app/(app)/workspace-actions";

export type FeedCompany = { id:string;name:string;domain:string;website_url:string|null;industry:string|null;country:string|null;headquarters:string|null;employee_range:string|null;funding_stage:string|null;description:string|null;match_explanation:string|null;verification_evidence:unknown;initial_icp_match_score:number|null;created_at:string;saved_at:string|null;status:string };
const values=(value:unknown)=>Array.isArray(value)?value.map(String).filter(Boolean):[];
function decisionMakers(range:string|null){const match=range?.match(/\d+/g)?.map(Number)||[];const largest=Math.max(0,...match);if(!largest||largest<=25)return["Founder","Growth Lead"];if(largest<=200)return["CMO","Head of Product Marketing","Head of Brand"];return["VP Marketing","Product Marketing Director","Customer Insights Lead"];}
function scoreColour(score:number){if(score>=80)return"bg-green-100 text-green-900";if(score>=70)return"bg-orange-100 text-orange-900";if(score>=60)return"bg-yellow-100 text-yellow-900";return"bg-slate-100 text-slate-700"}
function reasons(company:FeedCompany){const explanation=(company.match_explanation||"").split(/(?<=[.!?])\s+/).filter(Boolean);return[...explanation,...values(company.verification_evidence)].slice(0,5)}

export function ProspectCard({company}:{company:FeedCompany}){const score=company.initial_icp_match_score||0;const evidence=values(company.verification_evidence);const signals=evidence.slice(0,6);return <article className="card flex h-full flex-col overflow-hidden p-6">
  <div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#091f3c] text-lg font-extrabold text-white">{company.name.slice(0,2).toUpperCase()}</div><div className="min-w-0"><h2 className="truncate text-xl font-extrabold">{company.name}</h2><p className="truncate text-sm text-[#667085]">{company.industry||"Industry unknown"}</p></div></div><div className={`rounded-xl px-3 py-2 text-center ${scoreColour(score)}`}><div className="text-xl font-extrabold">{score}/100</div><div className="text-[10px] font-bold uppercase">Discovery Score</div></div></div>
  <div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-[#667085]"><span className="badge">{company.status.replaceAll("_"," ")}</span><span className="flex items-center gap-1"><MapPin size={14}/>{company.country||company.headquarters||"Location unknown"}</span><span className="flex items-center gap-1"><Users size={14}/>{company.employee_range||"Employees unknown"}</span>{company.funding_stage&&<span>{company.funding_stage}</span>}</div>
  <section className="mt-5"><h3 className="label">Why This Prospect Appeared</h3><ul className="mt-2 space-y-1 text-sm">{reasons(company).map((item,index)=><li key={`${item}-${index}`}>• {item}</li>)}</ul></section>
  <section className="mt-5"><h3 className="label">Buying Signals</h3><div className="mt-2 flex flex-wrap gap-2">{signals.length?signals.map((signal,index)=><span className="badge" key={`${signal}-${index}`}>{signal}</span>):<span className="text-sm text-[#667085]">No strong signal verified yet</span>}</div></section>
  <section className="mt-5"><h3 className="label">Why They Might Buy</h3><ul className="mt-2 space-y-1 text-sm">{reasons(company).slice(0,5).map((item,index)=><li key={`${item}-buy-${index}`}>• {item}</li>)}</ul></section>
  <section className="mt-5"><h3 className="label">Decision Makers</h3><div className="mt-2 flex flex-wrap gap-2">{decisionMakers(company.employee_range).map(role=><span className="badge" key={role}>{role}</span>)}</div></section>
  <div className="mt-auto flex flex-wrap gap-2 border-t border-[#e7eaf0] pt-5"><a className="button secondary gap-2" href={company.website_url||`https://${company.domain}`} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Open website</a>{company.saved_at?<form action={removeSavedProspect.bind(null,company.id)}><button className="button secondary">Remove saved</button></form>:<form action={saveProspect.bind(null,company.id)}><button className="button gap-2"><Star size={15}/>Save Prospect</button></form>}<form action={hideProspect.bind(null,company.id)}><button className="button secondary gap-2"><EyeOff size={15}/>Hide</button></form></div>
</article>}
