import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { getWorkspace } from "@/lib/workspace";
import { addCompany } from "../workspace-actions";

export default async function Discover() {
  const { supabase, organisationId } = await getWorkspace();
  const { data: icps } = await supabase.from("icps").select("id,name").eq("organisation_id", organisationId).eq("is_active", true).order("name");
  return <><PageHeader eyebrow="Prospect discovery" title="Discover genuine opportunities" description="Manual companies already use the approval pipeline. Automated search will be enabled separately."/><div className="grid gap-6 lg:grid-cols-2"><section className="card p-6"><h2 className="text-xl font-extrabold">Automated discovery</h2>{icps?.length?<label className="mt-5 block text-sm font-bold">Ideal customer profile<select className="mt-2" disabled><option>{icps.length} active ICPs available</option></select></label>:<div className="mt-5 rounded-xl border border-orange-200 bg-orange-50 p-4"><h3 className="font-extrabold">Create an ICP first</h3><p className="mt-1 text-sm text-[#667085]">Define the companies and signals you want to target before running discovery.</p><Link href="/icps/new" className="button mt-4">Create ICP</Link></div>}<button className="button mt-5 w-full opacity-50" disabled>Automated discovery coming in Phase 2</button><p className="mt-3 text-xs text-[#667085]">Tavily discovery will create an approval queue; snippets will not be treated as verified facts.</p></section><section className="card p-6"><h2 className="text-xl font-extrabold">Add a company manually</h2><form action={addCompany}><label className="mt-5 block text-sm font-bold">Company name<input name="name" className="mt-2" placeholder="Company name" required/></label><label className="mt-4 block text-sm font-bold">Website URL<input name="website_url" className="mt-2" type="url" placeholder="https://example.com" required/></label><button className="button secondary mt-5 w-full">Add to approval queue</button></form></section></div></>;
}
